version: '3.7'

services:
  ruby:
    image: ruby:3.1
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ruby main.rb
    restart: always
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}